
var neighbours = {
	"AK": [],
	"AL": ["FL", "GA", "MS", "TN"],
	"AR": ["LA", "MO", "MS", "OK", "TN", "TX"],
	"AZ": ["CA", "NM", "NV", "UT"],
	"CA": ["NV", "OR", "AZ"],
	"CO": ["KS", "NE", "NM", "OK", "UT", "WY"],
	"CT": ["MA", "NY", "RI"],
	"DC": ["MD", "VA"],
	"DE": ["MD", "NJ", "PA"],
	"FL": ["GA", "AL"],
	"GA": ["AL", "NC", "SC", "TN", "FL"],
	"HI": [],
	"IA": ["IL", "MN", "MO", "NE", "SD", "WI"],
	"ID": ["MT", "NV", "OR", "UT", "WA", "WY"],
	"IL": ["IN", "KY", "MO", "WI", "IA"],
	"IN": ["KY", "MI", "OH", "IL"],
	"KS": ["MO", "NE", "OK", "CO"],
	"KY": ["MO", "OH", "TN", "VA", "WV", "IN", "IL"],
	"LA": ["MS", "TX", "AR"],
	"MA": ["NH", "NY", "RI", "VT", "CT"],
	"MD": ["PA", "VA", "WV", "DC", "DE"],
	"ME": ["NH"],
	"MI": ["OH", "WI", "IN"],
	"MN": ["ND", "SD", "WI", "IA"],
	"MO": ["NE", "OK", "TN", "KS", "AR", "KY", "IA", "IL"],
	"MS": ["TN", "AL", "AR", "LA"],
	"MT": ["ND", "SD", "WY", "ID"],
	"NC": ["SC", "TN", "VA", "GA"],
	"ND": ["SD", "MN", "MT"],
	"NE": ["SD", "WY", "CO", "KS", "MO", "IA"],
	"NH": ["VT", "MA", "ME"],
	"NJ": ["NY", "PA", "DE"],
	"NM": ["OK", "TX", "CO", "AZ"],
	"NV": ["OR", "UT", "ID", "CA", "AZ"],
	"NY": ["PA", "VT", "MA", "CT", "NJ"],
	"OH": ["PA", "WV", "KY", "IN", "MI"],
	"OK": ["TX", "AR", "MO", "KS", "CO", "NM"],
	"OR": ["WA", "CA", "NV", "ID"],
	"PA": ["WV", "NJ", "MD", "NY", "DE", "OH"],
	"RI": ["CT", "MA"],
	"SC": ["NC", "GA"],
	"SD": ["WY", "MT", "ND", "MN", "IA", "NE"],
	"TN": ["VA", "KY", "NC", "GA", "MO", "AL", "MS", "AR"], 
	"TX": ["LA", "AR", "OK", "NM"],
	"UT": ["WY", "CO", "AZ", "NV", "ID"],
	"VA": ["WV", "MD", "KY", "TN", "NC", "DC"],
	"VT": ["NY", "MA", "NH"]
	"WA": ["ID", "OR"],
	"WV": ["PA", "MD", "VA", "KY", "OH"],
	"WI": ["MI", "IL", "IA", "MN"],
	"WY": ["MT", "SD", "NE", "CO", "UT", "ID"]
}